#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/smart_meeting
#    username: root
#    password: 123456
#  data:
#    redis:
#      host: localhost
#      port: 6379
#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
# server??
server:
  port: 8080
  servlet:
    context-path: /

# ?????
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/smart_meeting
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
  data:
      redis:
        host: localhost
        port: 6379

# mybatis-plus???
mybatis-plus:
  type-aliases-package: com.homework.pojo
  global-config:
    db-config:
      logic-delete-field: isDeleted  #??????
      id-type: auto #???????
      table-prefix: news_ # ??????

#jwt??
jwt:
  token:
    tokenExpiration: 120 #????,????
    tokenSignKey: headline123456  #???????? ???